name: GitHub Metrics

on:
  # Schedule daily updates (adjust cron as needed)
  schedule: [{cron: "0 0 * * *"}] # Runs daily at 00:00 UTC
  # Run workflow manually
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions: # <--- ADD THIS BLOCK
      contents: write # <--- THIS GRANTS WRITE PERMISSION
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: dannz510
          base: ""
          plugin_achievements: yes
          plugin_achievements_only: >-
            sponsor, maintainer, octonaut
          output_action: github_commit # This is correct for direct commit by the action
