name: GitHub Metrics

on:
  # Schedule daily updates (adjust cron as needed)
  schedule: [{cron: "0 0 * * *"}]
  # Run workflow manually
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: dannz510
          base: ""
          plugin_achievements: yes
          plugin_achievements_only: >-
            sponsor, maintainer, octonaut
          # plugin_achievements_display: detailed
          # plugin_achievements_threshold: C
          # plugin_achievements_secrets: yes
          plugin_achievements_ignored: projects # <--- ADD THIS LINE
