name: GitHub Metrics

on:
  # Schedule daily updates (adjust cron as needed)
  schedule: [{cron: "0 0 * * *"}] # Runs daily at 00:00 UTC
  # Run workflow manually
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.achievements.svg # This is the output file name
          token: ${{ secrets.METRICS_TOKEN }} # This secret needs to be created
          user: dannz510 # Your GitHub username
          base: "" # Don't fetch base stats (as we only want achievements here)
          plugin_achievements: yes # Enable the achievements plugin
          plugin_achievements_only: >-
            sponsor, maintainer, octonaut # Example: show specific achievements
          # plugin_achievements_display: detailed # Default is detailed
          # plugin_achievements_threshold: C # Default threshold
          # plugin_achievements_secrets: yes # Default is yes
