name: GitHub Metrics

on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          filename: metrics.plugin.achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: dannz510
          base: ""
          plugin_achievements: yes
          plugin_achievements_only: sponsor, maintainer, octonaut
          plugin_achievements_ignored: projects, manager
