name: Update Monkeytype Stats
on:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Monkeytype Stats Card
        uses: [name-of-the-new-action-here]
        with:
          monkeytype_username: "Dannzz"
          theme: "midnight"
          # Other options for more detailed stats
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update Monkeytype stats card" || echo "No changes to commit"
          git push
