name: generate monkeytype readme svg

on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours
  workflow_dispatch:

jobs:
  download-svg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Monkeytype Readme
        run: |
          mkdir public
          # Replace YOUR_MONKEYTYPE_USERNAME and THEME_NAME with your details
          curl -o public/monkeytype-readme.svg https://monkeytype-readme.com/generate-svg/Dannzz/midnight
      
      - name: Push monkeytype-readme.svg to the monkeytype-readme branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: monkeytype-readme
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
